name: C/C++ CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Check out the repository
          uses: actions/checkout@v2

        - name: Set up compiler
          uses: sudo apt-get install -y g++
        
        - name: Compile C++ file
          run: g++ newProj.cc -o newProj

        - name: Run C++ executable
          run: ./newProj
            
        # - name: Build
        #   run: |
        #     cmake -B build
        #     cmake --build build
        
        # - name: Test
        #   run: |
        #     cd build
        #     ctest
        - name: Upload Artifact
          uses: actions/upload-artifact@v2
          with:
            name: newProj-executable
            path: ./newProj
        


